# Copilot Coding Agent - Environment Setup
# This file configures the environment for GitHub Copilot's coding agent,
# enabling it to be assigned to issues and autonomously create pull requests.
#
# Docs: https://docs.github.com/en/copilot/using-github-copilot/using-copilot-coding-agent

setup:
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Install npm dependencies
    run: npm ci

  - name: Install Playwright browsers
    run: npx playwright install chromium --with-deps

  - name: Install Taskfile
    run: |
      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

  - name: Install Python tools (for complexity/security analysis)
    run: |
      pip install lizard bandit semgrep
