#!/usr/bin/env python3
"""Generate a Markdown complexity report from Lizard output."""

import os
import csv
from datetime import datetime

# Read CSV for high complexity items
high_complexity_items = []
if os.path.exists(".complexity-reports/complexity-report.csv"):
    with open(".complexity-reports/complexity-report.csv", "r") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) > 1:
                try:
                    ccn = int(row[1])
                    if ccn > 10:
                        high_complexity_items.append(row)
                except ValueError:
                    pass

# Generate markdown report
md_content = "# Code Complexity Analysis Report\n\n"
md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
md_content += "## Summary\n\n"

# Read raw report
if os.path.exists(".complexity-reports/complexity-report-raw.txt"):
    with open(".complexity-reports/complexity-report-raw.txt", "r") as f:
        raw_report = f.read()
    # Find the summary section
    lines = raw_report.split('\n')
    in_summary = False
    summary_lines = []
    for line in lines:
        if "No thresholds exceeded" in line or "thresholds exceeded" in line:
            summary_lines.append(line)
            break
        if in_summary:
            summary_lines.append(line)
        if "Total nloc" in line:
            in_summary = True
            summary_lines.append(line)
    
    if summary_lines:
        md_content += "```\n"
        md_content += "\n".join(summary_lines[:15])
        md_content += "\n```\n\n"

# Add high complexity section
if high_complexity_items:
    md_content += "## ⚠️ High Complexity Items (CCN > 10)\n\n"
    md_content += "| NLOC | CCN | Tokens | Params | Length | Location |\n"
    md_content += "|------|-----|--------|--------|--------|----------|\n"
    
    for item in high_complexity_items:
        if len(item) > 5:
            nloc = item[0]
            ccn = item[1]
            tokens = item[2]
            params = item[3]
            length = item[4]
            location = item[5].strip('"') if len(item) > 5 else "unknown"
            md_content += f"| {nloc} | {ccn} | {tokens} | {params} | {length} | `{location}` |\n"
else:
    md_content += "## ✅ Complexity Status\n\n"
    md_content += "No high-complexity items found (all CCN ≤ 10)\n\n"

# Add guidelines
md_content += "## Guidelines\n\n"
md_content += "- **Cyclomatic Complexity (CCN)**: Measure of code complexity based on decision points\n"
md_content += "  - **Good**: CCN ≤ 10\n"
md_content += "  - **Warning**: 10 < CCN ≤ 15\n"
md_content += "  - **Critical**: CCN > 15\n\n"
md_content += "- **Function Length (NLOC)**: Number of lines of code\n"
md_content += "  - Target: Keep functions under 50 lines\n"
md_content += "  - For this static template, code should be minimal\n\n"
md_content += "- **Threshold**: Any function with CCN > 10 should be reviewed and simplified\n\n"
md_content += "## More Information\n\n"
md_content += "- Generated by [Lizard](http://www.lizard.ws/)\n"
md_content += "- Reports location: `.complexity-reports/`\n"
md_content += "  - `complexity-report.md` (this file)\n"
md_content += "  - `complexity-report.csv` (machine-readable)\n"

# Write markdown report
with open(".complexity-reports/complexity-report.md", "w") as f:
    f.write(md_content)

print("✅ Markdown report generated")
