version: '3'

tasks:
  complexity:
    desc: Analyze code complexity using Lizard
    summary: |
      Performs code complexity analysis on the codebase using Lizard.
      Generates both text and CSV reports with configurable thresholds.
      
      Usage:
        task complexity           # Run analysis
        task complexity -- -v     # Verbose output
    cmds:
      - task: complexity:check-tool
      - task: complexity:analyze
      - task: complexity:report
    silent: false

  complexity:check-tool:
    desc: Check if Lizard is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v lizard &> /dev/null; then
          echo "📦 Installing Lizard..."
          
          INSTALL_SUCCESS=0
          
          if command -v pip3 &> /dev/null; then
            echo "Trying pip3..."
            if pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v pip &> /dev/null; then
            echo "Trying pip..."
            if pip install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v sudo &> /dev/null && command -v apt-get &> /dev/null; then
            echo "Trying apt-get..."
            if sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v brew &> /dev/null; then
            echo "Trying brew..."
            if brew install lizard; then
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Lizard with any available package manager"
            echo "Please install Lizard manually:"
            echo "  - pip install lizard"
            echo "  - brew install lizard"
            echo "  - https://github.com/terryyin/lizard"
            exit 1
          fi
        fi
        
        # Verify installation succeeded
        if ! command -v lizard &> /dev/null; then
          echo "❌ Lizard installed but not found in PATH"
          exit 1
        fi
        
        LIZARD_VERSION=$(lizard --version 2>&1)
        echo "✅ Lizard $LIZARD_VERSION"
    silent: false

  complexity:analyze:
    desc: Run Lizard analysis and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Analyzing code complexity..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        # Create reports directory
        mkdir -p .complexity-reports
        
        # Run lizard and generate text report (intermediate)
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          -o ".complexity-reports/complexity-report-raw.txt" \
          || true
        
        # Generate CSV report for structured data
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          --csv > ".complexity-reports/complexity-report.csv" \
          || true
        
        # Convert to markdown using Python
        python3 .scripts/generate-complexity-md.py
        
        echo "✅ Analysis complete"
    silent: false

  complexity:report:
    desc: Display formatted complexity report
    internal: true
    cmds:
      - |
        echo ""
        echo "📊 COMPLEXITY REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .complexity-reports/complexity-report.md ]; then
          echo "❌ Complexity report not generated!"
          echo "This indicates an error in the analysis step. Check the logs above."
          exit 1
        fi
        
        cat .complexity-reports/complexity-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .complexity-reports/"
        echo "   • complexity-report.md (human-readable)"
        echo "   • complexity-report.csv (machine-readable)"
        echo ""
        
        # Check for high complexity issues (CCN in column 2, indexed as $2)
        if [ -f .complexity-reports/complexity-report.csv ]; then
          HIGH_COMPLEXITY=$(awk -F',' '$2 > 10' .complexity-reports/complexity-report.csv | wc -l)
          if [ "$HIGH_COMPLEXITY" -gt 0 ]; then
            echo "⚠️  Found $HIGH_COMPLEXITY item(s) with cyclomatic complexity > 10"
            echo ""
          else
            echo "✅ No high-complexity items found (all CCN ≤ 10)"
            echo ""
          fi
        fi
    silent: false

  security:
    desc: Run all security checks (SAST, dependencies, DAST)
    summary: |
      Runs the full security suite: SAST (Semgrep), dependency scanning (Trivy),
      and DAST (OWASP ZAP).

      Usage:
        task security                           # Run all checks
        task sast                               # SAST only
        task dependencies                       # Dependency scan only
        task dast -- http://localhost:8080      # DAST only
    cmds:
      - task: sast
      - task: dependencies
      - task: dast
    silent: false

  sast:
    desc: Run static application security testing using Semgrep
    summary: |
      Performs SAST on the codebase using Semgrep.
      Generates both JSON and Markdown reports.

      Usage:
        task sast           # Run analysis
    cmds:
      - task: sast:check-tool
      - task: sast:analyze
      - task: sast:report
    silent: false

  sast:check-tool:
    desc: Check if Semgrep is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v semgrep &> /dev/null; then
          echo "📦 Installing Semgrep..."
          
          INSTALL_SUCCESS=0
          
          if command -v pip3 &> /dev/null; then
            echo "Trying pip3..."
            if pip3 install --user semgrep; then
              INSTALL_SUCCESS=1
            fi
          elif command -v pip &> /dev/null; then
            echo "Trying pip..."
            if pip install --user semgrep; then
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Semgrep"
            echo "Please install Semgrep manually:"
            echo "  - pip install semgrep"
            echo "  - https://semgrep.dev/docs/getting-started/"
            exit 1
          fi
        fi
        
        if ! command -v semgrep &> /dev/null; then
          echo "❌ Semgrep installed but not found in PATH"
          exit 1
        fi
        
        SEMGREP_VERSION=$(semgrep --version 2>&1)
        echo "✅ Semgrep $SEMGREP_VERSION"
    silent: false

  sast:analyze:
    desc: Run Semgrep SAST analysis and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Running SAST analysis..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        mkdir -p .sast-reports
        
        semgrep \
          --config=auto \
          --json \
          --output=".sast-reports/sast-report.json" \
          --exclude="node_modules" \
          --exclude=".git" \
          . \
          || true
        
        python3 .scripts/generate-sast-md.py
        
        echo "✅ Analysis complete"
    silent: false

  sast:report:
    desc: Display formatted SAST report
    internal: true
    cmds:
      - |
        echo ""
        echo "🔍 SAST REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .sast-reports/sast-report.md ]; then
          echo "❌ SAST report not generated!"
          exit 1
        fi
        
        cat .sast-reports/sast-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .sast-reports/"
        echo "   • sast-report.md (human-readable)"
        echo "   • sast-report.json (machine-readable)"
        echo ""
        
        if [ -f .sast-reports/sast-report.json ]; then
          ERROR_COUNT=$(python3 -c "
        import json, sys
        with open('.sast-reports/sast-report.json') as f:
          data = json.load(f)
        errors = [r for r in data.get('results', []) if r.get('extra', {}).get('severity', '').upper() == 'ERROR']
        print(len(errors))
        " 2>/dev/null || echo "0")
          if [ "$ERROR_COUNT" -gt 0 ]; then
            echo "⚠️  Found $ERROR_COUNT error-severity finding(s)"
            echo ""
          else
            echo "✅ No error-severity findings detected"
            echo ""
          fi
        fi
    silent: false

  dependencies:
    desc: Run dependency vulnerability scanning using Trivy
    summary: |
      Scans project dependencies for known CVEs using Trivy.
      Generates both JSON and Markdown reports.

      Usage:
        task dependencies           # Run scan
    cmds:
      - task: dependencies:check-tool
      - task: dependencies:analyze
      - task: dependencies:report
    silent: false

  dependencies:check-tool:
    desc: Check if Trivy is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v trivy &> /dev/null; then
          echo "📦 Installing Trivy..."
          
          INSTALL_SUCCESS=0
          
          if command -v curl &> /dev/null; then
            echo "Trying install script..."
            if curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ~/.local/bin; then
              export PATH="$PATH:$HOME/.local/bin"
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Trivy"
            echo "Please install Trivy manually:"
            echo "  - https://trivy.dev/latest/getting-started/installation/"
            exit 1
          fi
        fi
        
        if ! command -v trivy &> /dev/null; then
          echo "❌ Trivy installed but not found in PATH"
          exit 1
        fi
        
        TRIVY_VERSION=$(trivy --version 2>&1 | head -1)
        echo "✅ $TRIVY_VERSION"
    silent: false

  dependencies:analyze:
    desc: Run Trivy dependency scan and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Scanning dependencies for vulnerabilities..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        mkdir -p .dependencies-reports
        
        trivy fs \
          --format json \
          --output ".dependencies-reports/dependencies-report.json" \
          --skip-dirs node_modules \
          --skip-dirs .git \
          . \
          || true
        
        python3 .scripts/generate-dependencies-md.py
        
        echo "✅ Scan complete"
    silent: false

  dependencies:report:
    desc: Display formatted dependency vulnerability report
    internal: true
    cmds:
      - |
        echo ""
        echo "📦 DEPENDENCY VULNERABILITY REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .dependencies-reports/dependencies-report.md ]; then
          echo "❌ Dependency report not generated!"
          exit 1
        fi
        
        cat .dependencies-reports/dependencies-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .dependencies-reports/"
        echo "   • dependencies-report.md (human-readable)"
        echo "   • dependencies-report.json (machine-readable)"
        echo ""
        
        if [ -f .dependencies-reports/dependencies-report.json ]; then
          VULN_COUNT=$(python3 -c "
        import json, sys
        with open('.dependencies-reports/dependencies-report.json') as f:
          data = json.load(f)
        count = 0
        for r in data.get('Results', []):
          for v in r.get('Vulnerabilities', []):
            if v.get('Severity', '').upper() in ('CRITICAL', 'HIGH'):
              count += 1
        print(count)
        " 2>/dev/null || echo "0")
          if [ "$VULN_COUNT" -gt 0 ]; then
            echo "⚠️  Found $VULN_COUNT CRITICAL/HIGH vulnerability(ies)"
            echo ""
          else
            echo "✅ No CRITICAL/HIGH vulnerabilities detected"
            echo ""
          fi
        fi
    silent: false

  dast:
    desc: Run dynamic application security testing using OWASP ZAP
    summary: |
      Performs DAST against a running site using OWASP ZAP (requires Docker).
      Generates both JSON and Markdown reports.

      Usage:
        task start &                           # Start site first
        task dast -- http://localhost:8080     # Then run DAST
    vars:
      TARGET: '{{default "http://localhost:8080" .CLI_ARGS}}'
    cmds:
      - task: dast:check-tool
      - task: dast:analyze
        vars:
          TARGET: '{{.TARGET}}'
      - task: dast:report
    silent: false

  dast:check-tool:
    desc: Check if Docker (for ZAP) is available
    internal: true
    cmds:
      - |
        if ! command -v docker &> /dev/null; then
          echo "❌ Docker is required to run OWASP ZAP"
          echo "Please install Docker: https://docs.docker.com/get-docker/"
          exit 1
        fi
        
        DOCKER_VERSION=$(docker --version 2>&1)
        echo "✅ $DOCKER_VERSION"
    silent: false

  dast:analyze:
    desc: Run OWASP ZAP baseline scan and generate reports
    internal: true
    dir: .
    vars:
      TARGET: '{{default "http://localhost:8080" .TARGET}}'
    cmds:
      - |
        echo ""
        echo "🌐 Running DAST analysis against {{.TARGET}}..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        mkdir -p .dast-reports
        
        docker run --rm \
          --network host \
          -v "$(pwd)/.dast-reports:/zap/wrk/:rw" \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t "{{.TARGET}}" \
          -J "/zap/wrk/dast-report.json" \
          -I \
          || true
        
        python3 .scripts/generate-dast-md.py
        
        echo "✅ Analysis complete"
    silent: false

  dast:report:
    desc: Display formatted DAST report
    internal: true
    cmds:
      - |
        echo ""
        echo "🌐 DAST REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .dast-reports/dast-report.md ]; then
          echo "❌ DAST report not generated!"
          exit 1
        fi
        
        cat .dast-reports/dast-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .dast-reports/"
        echo "   • dast-report.md (human-readable)"
        echo "   • dast-report.json (machine-readable)"
        echo ""
        
        if [ -f .dast-reports/dast-report.json ]; then
          ALERT_COUNT=$(python3 -c "
        import json, sys
        with open('.dast-reports/dast-report.json') as f:
          data = json.load(f)
        count = 0
        for site in data.get('site', []):
          for alert in site.get('alerts', []):
            if int(alert.get('riskcode', 0)) >= 2:
              count += 1
        print(count)
        " 2>/dev/null || echo "0")
          if [ "$ALERT_COUNT" -gt 0 ]; then
            echo "⚠️  Found $ALERT_COUNT medium/high alert(s)"
            echo ""
          else
            echo "✅ No medium/high alerts detected"
            echo ""
          fi
        fi
    silent: false

  test:
    desc: Run Playwright tests
    cmds:
      - npx playwright test {{.CLI_ARGS}}

  test:headed:
    desc: Run Playwright tests with headed browser
    cmds:
      - npx playwright test --headed {{.CLI_ARGS}}

  test:complexity:
    desc: Run complexity report generation tests
    cmds:
      - python3 tests/generate_complexity_report.test.py

  test:security:
    desc: Run all security report generation tests
    cmds:
      - task: test:sast
      - task: test:dependencies
      - task: test:dast

  test:sast:
    desc: Run SAST report generation tests
    cmds:
      - python3 tests/generate_sast_report.test.py

  test:dependencies:
    desc: Run dependency vulnerability report generation tests
    cmds:
      - python3 tests/generate_dependencies_report.test.py

  test:dast:
    desc: Run DAST report generation tests
    cmds:
      - python3 tests/generate_dast_report.test.py

  start:
    desc: Start local development server
    cmds:
      - npx http-server . -p 8080 -o
