version: '3'

tasks:
  complexity:
    desc: Analyze code complexity using Lizard
    summary: |
      Performs code complexity analysis on the codebase using Lizard.
      Generates both text and CSV reports with configurable thresholds.
      
      Usage:
        task complexity           # Run analysis
        task complexity -- -v     # Verbose output
    cmds:
      - task: complexity:check-tool
      - task: complexity:analyze
      - task: complexity:report
    silent: false

  complexity:check-tool:
    desc: Check if Lizard is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v lizard &> /dev/null; then
          echo "📦 Installing Lizard..."
          
          INSTALL_SUCCESS=0
          
          if command -v pip3 &> /dev/null; then
            echo "Trying pip3..."
            if pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v pip &> /dev/null; then
            echo "Trying pip..."
            if pip install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v sudo &> /dev/null && command -v apt-get &> /dev/null; then
            echo "Trying apt-get..."
            if sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v brew &> /dev/null; then
            echo "Trying brew..."
            if brew install lizard; then
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Lizard with any available package manager"
            echo "Please install Lizard manually:"
            echo "  - pip install lizard"
            echo "  - brew install lizard"
            echo "  - https://github.com/terryyin/lizard"
            exit 1
          fi
        fi
        
        # Verify installation succeeded
        if ! command -v lizard &> /dev/null; then
          echo "❌ Lizard installed but not found in PATH"
          exit 1
        fi
        
        LIZARD_VERSION=$(lizard --version 2>&1)
        echo "✅ Lizard $LIZARD_VERSION"
    silent: false

  complexity:analyze:
    desc: Run Lizard analysis and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Analyzing code complexity..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        # Create reports directory
        mkdir -p .complexity-reports
        
        # Run lizard and generate text report (intermediate)
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          -o ".complexity-reports/complexity-report-raw.txt" \
          || true
        
        # Generate CSV report for structured data
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          --csv > ".complexity-reports/complexity-report.csv" \
          || true
        
        # Convert to markdown using Python
        python3 .scripts/generate-complexity-md.py
        
        echo "✅ Analysis complete"
    silent: false

  complexity:report:
    desc: Display formatted complexity report
    internal: true
    cmds:
      - |
        echo ""
        echo "📊 COMPLEXITY REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .complexity-reports/complexity-report.md ]; then
          echo "❌ Complexity report not generated!"
          echo "This indicates an error in the analysis step. Check the logs above."
          exit 1
        fi
        
        cat .complexity-reports/complexity-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .complexity-reports/"
        echo "   • complexity-report.md (human-readable)"
        echo "   • complexity-report.csv (machine-readable)"
        echo ""
        
        # Check for high complexity issues (CCN in column 2, indexed as $2)
        if [ -f .complexity-reports/complexity-report.csv ]; then
          HIGH_COMPLEXITY=$(awk -F',' '$2 > 10' .complexity-reports/complexity-report.csv | wc -l)
          if [ "$HIGH_COMPLEXITY" -gt 0 ]; then
            echo "⚠️  Found $HIGH_COMPLEXITY item(s) with cyclomatic complexity > 10"
            echo ""
          else
            echo "✅ No high-complexity items found (all CCN ≤ 10)"
            echo ""
          fi
        fi
    silent: false

  owasp:
    desc: Run OWASP dependency check
    summary: |
      Performs OWASP dependency vulnerability analysis using Dependency-Check.
      Downloads Dependency-Check CLI if not already installed.
      
      Usage:
        task owasp           # Run analysis
    cmds:
      - task: owasp:check-tool
      - task: owasp:analyze
      - task: owasp:report
    silent: false

  owasp:check-tool:
    desc: Check if OWASP Dependency-Check is installed, install if necessary
    internal: true
    cmds:
      - |
        if command -v dependency-check &> /dev/null; then
          echo "✅ dependency-check available"
          exit 0
        fi
        
        if [ -f ".owasp-tool/dependency-check/bin/dependency-check.sh" ]; then
          echo "✅ dependency-check found in .owasp-tool/"
          exit 0
        fi
        
        if ! command -v java &> /dev/null; then
          echo "❌ Java is required to run OWASP Dependency-Check"
          echo "Please install Java: https://adoptium.net/"
          exit 1
        fi
        
        OWASP_VERSION="9.0.9"
        echo "📦 Installing OWASP Dependency-Check ${OWASP_VERSION}..."
        
        mkdir -p .owasp-tool
        
        DOWNLOAD_URL="https://github.com/jeremylong/DependencyCheck/releases/download/v${OWASP_VERSION}/dependency-check-${OWASP_VERSION}-release.zip"
        
        INSTALL_SUCCESS=0
        
        if command -v curl &> /dev/null; then
          if curl -sL "$DOWNLOAD_URL" -o .owasp-tool/dc.zip; then
            INSTALL_SUCCESS=1
          fi
        elif command -v wget &> /dev/null; then
          if wget -q "$DOWNLOAD_URL" -O .owasp-tool/dc.zip; then
            INSTALL_SUCCESS=1
          fi
        fi
        
        if [ $INSTALL_SUCCESS -eq 0 ]; then
          echo "❌ Failed to download OWASP Dependency-Check"
          echo "Please install manually: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/"
          exit 1
        fi
        
        unzip -q .owasp-tool/dc.zip -d .owasp-tool
        rm .owasp-tool/dc.zip
        chmod +x .owasp-tool/dependency-check/bin/dependency-check.sh
        
        echo "✅ OWASP Dependency-Check ${OWASP_VERSION} installed to .owasp-tool/"
    silent: false

  owasp:analyze:
    desc: Run OWASP dependency check analysis
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Analyzing dependencies for vulnerabilities..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        # Find dependency-check command
        if command -v dependency-check &> /dev/null; then
          DC_CMD="dependency-check"
        elif [ -f ".owasp-tool/dependency-check/bin/dependency-check.sh" ]; then
          DC_CMD=".owasp-tool/dependency-check/bin/dependency-check.sh"
        else
          echo "❌ dependency-check not found. Run 'task owasp' to install."
          exit 1
        fi
        
        # Create reports directory
        mkdir -p .owasp-reports
        
        # Run dependency-check
        "$DC_CMD" \
          --project "template-netlify" \
          --scan . \
          --exclude ".git/**" \
          --exclude ".owasp-tool/**" \
          --exclude "node_modules/**" \
          --exclude ".owasp-reports/**" \
          --format JSON \
          --out ".owasp-reports" \
          || true
        
        # Convert to markdown
        python3 .scripts/generate-owasp-md.py
        
        echo "✅ OWASP analysis complete"
    silent: false

  owasp:report:
    desc: Display formatted OWASP report
    internal: true
    cmds:
      - |
        echo ""
        echo "🔒 OWASP DEPENDENCY CHECK REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .owasp-reports/owasp-report.md ]; then
          echo "❌ OWASP report not generated!"
          echo "This indicates an error in the analysis step. Check the logs above."
          exit 1
        fi
        
        cat .owasp-reports/owasp-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .owasp-reports/"
        echo "   • owasp-report.md (human-readable)"
        echo "   • dependency-check-report.json (machine-readable)"
        echo ""
        
        # Check for CRITICAL/HIGH vulnerabilities
        if [ -f .owasp-reports/dependency-check-report.json ]; then
          HIGH_COUNT=$(python3 -c "import json; data=json.load(open('.owasp-reports/dependency-check-report.json')); print(sum(1 for dep in data.get('dependencies',[]) for v in dep.get('vulnerabilities',[]) if v.get('severity','').upper() in ('CRITICAL','HIGH')))" 2>/dev/null || echo "0")
          if [ "$HIGH_COUNT" -gt 0 ]; then
            echo "⚠️  Found $HIGH_COUNT CRITICAL/HIGH vulnerability(ies)"
            echo ""
          else
            echo "✅ No CRITICAL/HIGH vulnerabilities found"
            echo ""
          fi
        fi
    silent: false

  test:
    desc: Run Playwright tests
    cmds:
      - npx playwright test {{.CLI_ARGS}}

  test:headed:
    desc: Run Playwright tests with headed browser
    cmds:
      - npx playwright test --headed {{.CLI_ARGS}}

  test:complexity:
    desc: Run complexity report generation tests
    cmds:
      - python3 tests/generate_complexity_report.test.py

  test:owasp:
    desc: Run OWASP report generation tests
    cmds:
      - python3 tests/generate_owasp_report.test.py

  start:
    desc: Start local development server
    cmds:
      - npx http-server . -p 8080 -o
