version: '3'

tasks:
  complexity:
    desc: Analyze code complexity using Lizard
    summary: |
      Performs code complexity analysis on the codebase using Lizard.
      Generates both text and CSV reports with configurable thresholds.
      
      Usage:
        task complexity           # Run analysis
        task complexity -- -v     # Verbose output
    cmds:
      - task: complexity:check-tool
      - task: complexity:analyze
      - task: complexity:report
    silent: false

  complexity:check-tool:
    desc: Check if Lizard is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v lizard &> /dev/null; then
          echo "📦 Installing Lizard..."
          
          INSTALL_SUCCESS=0
          
          if command -v pip3 &> /dev/null; then
            echo "Trying pip3..."
            if pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v pip &> /dev/null; then
            echo "Trying pip..."
            if pip install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v sudo &> /dev/null && command -v apt-get &> /dev/null; then
            echo "Trying apt-get..."
            if sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install --user lizard; then
              INSTALL_SUCCESS=1
            fi
          elif command -v brew &> /dev/null; then
            echo "Trying brew..."
            if brew install lizard; then
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Lizard with any available package manager"
            echo "Please install Lizard manually:"
            echo "  - pip install lizard"
            echo "  - brew install lizard"
            echo "  - https://github.com/terryyin/lizard"
            exit 1
          fi
        fi
        
        # Verify installation succeeded
        if ! command -v lizard &> /dev/null; then
          echo "❌ Lizard installed but not found in PATH"
          exit 1
        fi
        
        LIZARD_VERSION=$(lizard --version 2>&1)
        echo "✅ Lizard $LIZARD_VERSION"
    silent: false

  complexity:analyze:
    desc: Run Lizard analysis and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Analyzing code complexity..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        # Create reports directory
        mkdir -p .complexity-reports
        
        # Run lizard and generate text report (intermediate)
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          -o ".complexity-reports/complexity-report-raw.txt" \
          || true
        
        # Generate CSV report for structured data
        lizard . \
          -x "tests/*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x ".git/*" \
          --csv > ".complexity-reports/complexity-report.csv" \
          || true
        
        # Convert to markdown using Python
        python3 .scripts/generate-complexity-md.py
        
        echo "✅ Analysis complete"
    silent: false

  complexity:report:
    desc: Display formatted complexity report
    internal: true
    cmds:
      - |
        echo ""
        echo "📊 COMPLEXITY REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .complexity-reports/complexity-report.md ]; then
          echo "❌ Complexity report not generated!"
          echo "This indicates an error in the analysis step. Check the logs above."
          exit 1
        fi
        
        cat .complexity-reports/complexity-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .complexity-reports/"
        echo "   • complexity-report.md (human-readable)"
        echo "   • complexity-report.csv (machine-readable)"
        echo ""
        
        # Check for high complexity issues (CCN in column 2, indexed as $2)
        if [ -f .complexity-reports/complexity-report.csv ]; then
          HIGH_COMPLEXITY=$(awk -F',' '$2 > 10' .complexity-reports/complexity-report.csv | wc -l)
          if [ "$HIGH_COMPLEXITY" -gt 0 ]; then
            echo "⚠️  Found $HIGH_COMPLEXITY item(s) with cyclomatic complexity > 10"
            echo ""
          else
            echo "✅ No high-complexity items found (all CCN ≤ 10)"
            echo ""
          fi
        fi
    silent: false

  semgrep:
    desc: Run Semgrep security analysis
    summary: |
      Performs static analysis using Semgrep with auto-configured rules.
      Generates both JSON and Markdown reports.
      
      Usage:
        task semgrep           # Run analysis
    cmds:
      - task: semgrep:check-tool
      - task: semgrep:analyze
      - task: semgrep:report
    silent: false

  semgrep:check-tool:
    desc: Check if Semgrep is installed, install if necessary
    internal: true
    cmds:
      - |
        if ! command -v semgrep &> /dev/null; then
          echo "📦 Installing Semgrep..."
          
          INSTALL_SUCCESS=0
          
          if command -v pip3 &> /dev/null; then
            echo "Trying pip3..."
            if pip3 install --user semgrep; then
              INSTALL_SUCCESS=1
            fi
          elif command -v pip &> /dev/null; then
            echo "Trying pip..."
            if pip install --user semgrep; then
              INSTALL_SUCCESS=1
            fi
          fi
          
          if [ $INSTALL_SUCCESS -eq 0 ]; then
            echo "❌ Failed to install Semgrep"
            echo "Please install Semgrep manually:"
            echo "  - pip install semgrep"
            echo "  - https://semgrep.dev/docs/getting-started/"
            exit 1
          fi
        fi
        
        if ! command -v semgrep &> /dev/null; then
          echo "❌ Semgrep installed but not found in PATH"
          exit 1
        fi
        
        SEMGREP_VERSION=$(semgrep --version 2>&1)
        echo "✅ Semgrep $SEMGREP_VERSION"
    silent: false

  semgrep:analyze:
    desc: Run Semgrep analysis and generate reports
    internal: true
    dir: .
    cmds:
      - |
        echo ""
        echo "🔍 Running Semgrep security analysis..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        # Create reports directory
        mkdir -p .semgrep-reports
        
        # Run semgrep with auto config and JSON output
        semgrep \
          --config=auto \
          --json \
          --output=".semgrep-reports/semgrep-report.json" \
          --exclude="node_modules" \
          --exclude=".git" \
          . \
          || true
        
        # Convert to markdown using Python
        python3 .scripts/generate-semgrep-md.py
        
        echo "✅ Analysis complete"
    silent: false

  semgrep:report:
    desc: Display formatted Semgrep report
    internal: true
    cmds:
      - |
        echo ""
        echo "🔒 SEMGREP REPORT"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        if [ ! -f .semgrep-reports/semgrep-report.md ]; then
          echo "❌ Semgrep report not generated!"
          echo "This indicates an error in the analysis step. Check the logs above."
          exit 1
        fi
        
        cat .semgrep-reports/semgrep-report.md
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "📁 Reports saved to: .semgrep-reports/"
        echo "   • semgrep-report.md (human-readable)"
        echo "   • semgrep-report.json (machine-readable)"
        echo ""
        
        if [ -f .semgrep-reports/semgrep-report.json ]; then
          ERROR_COUNT=$(python3 -c "
        import json, sys
        with open('.semgrep-reports/semgrep-report.json') as f:
          data = json.load(f)
        errors = [r for r in data.get('results', []) if r.get('extra', {}).get('severity', '').upper() == 'ERROR']
        print(len(errors))
        " 2>/dev/null || echo "0")
          if [ "$ERROR_COUNT" -gt 0 ]; then
            echo "⚠️  Found $ERROR_COUNT error-severity finding(s)"
            echo ""
          else
            echo "✅ No error-severity findings detected"
            echo ""
          fi
        fi
    silent: false

  test:
    desc: Run Playwright tests
    cmds:
      - npx playwright test {{.CLI_ARGS}}

  test:headed:
    desc: Run Playwright tests with headed browser
    cmds:
      - npx playwright test --headed {{.CLI_ARGS}}

  test:complexity:
    desc: Run complexity report generation tests
    cmds:
      - python3 tests/generate_complexity_report.test.py

  test:semgrep:
    desc: Run Semgrep report generation tests
    cmds:
      - python3 tests/generate_semgrep_report.test.py

  start:
    desc: Start local development server
    cmds:
      - npx http-server . -p 8080 -o
