"""Tests for the secrets report generation script."""

import json
import os
import sys
import tempfile
import shutil
import subprocess
from pathlib import Path


SCRIPT_PATH = str(Path(__file__).parent.parent / ".scripts" / "generate-secrets-report.py")


def setup_test_env():
    """Create a temporary directory for test files."""
    tmpdir = tempfile.mkdtemp()
    os.chdir(tmpdir)
    os.makedirs(".secrets-reports", exist_ok=True)
    return tmpdir


def teardown_test_env(tmpdir):
    """Clean up temporary test directory."""
    os.chdir("/")
    shutil.rmtree(tmpdir, ignore_errors=True)


def run_script(tmpdir):
    """Run the generate-secrets-report.py script in tmpdir."""
    return subprocess.run(
        ["python3", SCRIPT_PATH],
        capture_output=True,
        text=True,
        cwd=tmpdir,
    )


def test_missing_json_fails():
    """Test that script fails when JSON report is missing."""
    tmpdir = setup_test_env()
    try:
        result = run_script(tmpdir)

        assert result.returncode != 0, "Script should fail when JSON report is missing"
        assert "JSON report not found" in result.stderr, "Should report missing JSON"
        assert not os.path.exists(".secrets-reports/secrets-report.md"), \
            "Should not generate report on error"

        print("✅ test_missing_json_fails passed")
    finally:
        teardown_test_env(tmpdir)


def test_generates_clean_report():
    """Test that script generates a clean report when no findings exist."""
    tmpdir = setup_test_env()
    try:
        with open(".secrets-reports/secrets-report.json", "w") as f:
            json.dump([], f)

        result = run_script(tmpdir)

        assert result.returncode == 0, f"Script should succeed. stderr: {result.stderr}"
        assert os.path.exists(".secrets-reports/secrets-report.md"), \
            "Should generate markdown report"

        with open(".secrets-reports/secrets-report.md", "r") as f:
            content = f.read()

        assert "Secrets Scan Report" in content, "Should have title"
        assert "✅ Clean" in content, "Should show clean status"
        assert "No secrets or credentials detected" in content, "Should indicate clean status"

        print("✅ test_generates_clean_report passed")
    finally:
        teardown_test_env(tmpdir)


def test_identifies_findings():
    """Test that script lists findings when secrets are detected."""
    tmpdir = setup_test_env()
    try:
        findings = [
            {
                "RuleID": "generic-api-key",
                "Description": "Generic API Key",
                "File": "config.py",
                "StartLine": 5,
                "EndLine": 5,
                "Match": "api_key = 'REDACTED'",
                "Secret": "REDACTED",
                "Commit": "abc123",
                "Author": "Dev",
                "Email": "dev@example.com",
                "Date": "2024-01-01",
                "Fingerprint": "abc123:config.py:generic-api-key:5",
            }
        ]
        with open(".secrets-reports/secrets-report.json", "w") as f:
            json.dump(findings, f)

        result = run_script(tmpdir)

        assert result.returncode == 0, f"Script should succeed. stderr: {result.stderr}"

        with open(".secrets-reports/secrets-report.md", "r") as f:
            content = f.read()

        assert "Secrets Detected" in content, "Should indicate secrets were found"
        assert "generic-api-key" in content, "Should list rule ID"
        assert "config.py" in content, "Should list affected file"
        assert "1 finding(s)" in content, "Should show finding count"

        print("✅ test_identifies_findings passed")
    finally:
        teardown_test_env(tmpdir)


def test_report_includes_guidelines():
    """Test that report includes guidelines."""
    tmpdir = setup_test_env()
    try:
        with open(".secrets-reports/secrets-report.json", "w") as f:
            json.dump([], f)

        result = run_script(tmpdir)

        assert result.returncode == 0, f"Script should succeed. stderr: {result.stderr}"

        with open(".secrets-reports/secrets-report.md", "r") as f:
            content = f.read()

        assert "Guidelines" in content, "Should include guidelines"
        assert "Never commit secrets" in content, "Should advise against committing secrets"
        assert "Generated by [Gitleaks]" in content, "Should credit Gitleaks"

        print("✅ test_report_includes_guidelines passed")
    finally:
        teardown_test_env(tmpdir)


def test_empty_json_file_treated_as_clean():
    """Test that an empty JSON file is treated as no findings."""
    tmpdir = setup_test_env()
    try:
        with open(".secrets-reports/secrets-report.json", "w") as f:
            f.write("")

        result = run_script(tmpdir)

        assert result.returncode == 0, f"Script should succeed on empty file. stderr: {result.stderr}"

        with open(".secrets-reports/secrets-report.md", "r") as f:
            content = f.read()

        assert "No secrets or credentials detected" in content, \
            "Empty file should be treated as clean"

        print("✅ test_empty_json_file_treated_as_clean passed")
    finally:
        teardown_test_env(tmpdir)


if __name__ == "__main__":
    print("\n🧪 Running secrets report script tests...\n")

    try:
        test_missing_json_fails()
        test_generates_clean_report()
        test_identifies_findings()
        test_report_includes_guidelines()
        test_empty_json_file_treated_as_clean()

        print("\n✅ All tests passed!\n")
        sys.exit(0)
    except AssertionError as e:
        print(f"\n❌ Test failed: {e}\n")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}\n")
        import traceback
        traceback.print_exc()
        sys.exit(1)
