#!/usr/bin/env python3
"""Generate a Markdown secrets report from Gitleaks JSON output.

This script is used both locally (via 'task gitleaks') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import json
import os
import sys
import traceback
from datetime import datetime


def read_json_report(json_path):
    """Read Gitleaks JSON report and return findings."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            content = f.read().strip()
            if not content:
                return []
            findings = json.loads(content)
            return findings if isinstance(findings, list) else []
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Failed to parse JSON report: {e}") from e
    except Exception as e:
        raise RuntimeError(f"Failed to read JSON report: {e}") from e


def format_findings_section(findings):
    """Format findings section for markdown."""
    if not findings:
        return "## ✅ Secrets Scan Status\n\nNo secrets or credentials detected.\n\n"

    result = f"## 🔴 Secrets Detected ({len(findings)} finding(s))\n\n"
    result += "| Rule | File | Line | Description |\n"
    result += "|------|------|------|-------------|\n"

    for finding in findings:
        rule_id = finding.get("RuleID", "unknown")
        file_path = finding.get("File", "unknown")
        start_line = finding.get("StartLine", "?")
        description = finding.get("Description", "")
        result += f"| `{rule_id}` | `{file_path}` | {start_line} | {description} |\n"

    result += "\n> ⚠️ **Action required:** Remove or rotate any exposed secrets immediately.\n\n"
    return result


def build_markdown_report(findings):
    """Build the complete markdown report."""
    md_content = "# Secrets Scan Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"
    md_content += f"- **Findings**: {len(findings)}\n"
    md_content += f"- **Status**: {'🔴 Secrets detected' if findings else '✅ Clean'}\n\n"

    md_content += format_findings_section(findings)

    md_content += "## Guidelines\n\n"
    md_content += "- **Never commit secrets** (API keys, tokens, passwords) to source control\n"
    md_content += "- Use environment variables or secret managers for sensitive values\n"
    md_content += "- If a secret was committed, rotate it immediately—even after removal from git history\n"
    md_content += "- Use `.gitleaksignore` to suppress known false positives\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [Gitleaks](https://github.com/gitleaks/gitleaks)\n"
    md_content += "- Reports location: `.gitleaks-reports/`\n"
    md_content += "  - `gitleaks-report.md` (this file)\n"
    md_content += "  - `gitleaks-report.json` (machine-readable)\n"

    return md_content


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from Gitleaks JSON output."""
    os.makedirs(".gitleaks-reports", exist_ok=True)

    json_path = ".gitleaks-reports/gitleaks-report.json"
    report_path = ".gitleaks-reports/gitleaks-report.md"

    findings = read_json_report(json_path)

    report_content = build_markdown_report(findings)
    write_report(report_path, report_content)

    print("✅ Markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
