#!/usr/bin/env python3
"""Generate a Markdown SAST report from Semgrep JSON output.

This script is used both locally (via 'task sast') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import json
import os
import sys
import traceback
from datetime import datetime


def read_json_report(json_path):
    """Read Semgrep JSON report and return findings."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"SAST JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read SAST JSON report: {e}") from e

    return data


def categorize_findings(results):
    """Separate findings into errors and warnings."""
    errors = []
    warnings = []

    for finding in results:
        severity = finding.get("extra", {}).get("severity", "").upper()
        if severity == "ERROR":
            errors.append(finding)
        else:
            warnings.append(finding)

    return errors, warnings


def format_finding_row(finding):
    """Format a single finding as a markdown table row."""
    check_id = finding.get("check_id", "unknown")
    path = finding.get("path", "unknown")
    start_line = finding.get("start", {}).get("line", "?")
    message = finding.get("extra", {}).get("message", "").replace("\n", " ").strip()
    severity = finding.get("extra", {}).get("severity", "unknown")
    location = f"`{path}:{start_line}`"
    truncated = (message[:77] + "...") if len(message) > 80 else message
    return f"| {check_id} | {severity} | {location} | {truncated} |"


def format_findings_section(findings, section_title, icon):
    """Format a list of findings as a markdown section."""
    if not findings:
        return ""

    result = f"## {icon} {section_title}\n\n"
    result += "| Rule | Severity | Location | Message |\n"
    result += "|------|----------|----------|---------|\n"
    for finding in findings:
        result += format_finding_row(finding) + "\n"
    result += "\n"
    return result


def build_markdown_report(data):
    """Build the complete markdown report from Semgrep JSON output."""
    results = data.get("results", [])
    errors = data.get("errors", [])

    error_findings, warning_findings = categorize_findings(results)
    total_findings = len(results)

    md_content = "# SAST Analysis Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"

    if errors:
        md_content += f"> ⚠️ Semgrep encountered {len(errors)} scan error(s). Results may be incomplete.\n\n"

    if total_findings == 0:
        md_content += "## ✅ SAST Status\n\nNo findings detected.\n\n"
    else:
        md_content += "| Metric | Count |\n"
        md_content += "|--------|-------|\n"
        md_content += f"| Total findings | {total_findings} |\n"
        md_content += f"| Errors | {len(error_findings)} |\n"
        md_content += f"| Warnings | {len(warning_findings)} |\n\n"

        md_content += format_findings_section(error_findings, "Error Findings", "🔴")
        md_content += format_findings_section(warning_findings, "Warning Findings", "⚠️")

    md_content += "## Guidelines\n\n"
    md_content += "- **Errors**: Must be reviewed and addressed before merging\n"
    md_content += "- **Warnings**: Should be reviewed; may indicate potential issues\n"
    md_content += "- Run `task sast` locally to reproduce findings\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [Semgrep](https://semgrep.dev/)\n"
    md_content += "- Reports location: `.sast-reports/`\n"
    md_content += "  - `sast-report.md` (this file)\n"
    md_content += "  - `sast-report.json` (machine-readable)\n"

    return md_content, len(error_findings)


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from Semgrep JSON output."""
    os.makedirs(".sast-reports", exist_ok=True)

    json_path = ".sast-reports/sast-report.json"
    report_path = ".sast-reports/sast-report.md"

    data = read_json_report(json_path)
    report_content, error_count = build_markdown_report(data)
    write_report(report_path, report_content)

    print("✅ Markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
