#!/usr/bin/env python3
"""Generate a Markdown OWASP dependency check report from dependency-check JSON output.

This script is used both locally (via 'task owasp') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import os
import json
from datetime import datetime
import sys
import traceback


def read_json_report(json_path):
    """Read OWASP dependency check JSON report."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            return json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read JSON report: {e}") from e


def extract_vulnerabilities(report):
    """Extract vulnerabilities from report, organized by severity."""
    vulns_by_severity = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": []}

    for dep in report.get("dependencies", []):
        dep_name = dep.get("fileName", "unknown")
        for vuln in dep.get("vulnerabilities", []):
            severity = vuln.get("severity", "UNKNOWN").upper()
            if severity not in vulns_by_severity:
                continue

            cvss_score = "N/A"
            if "cvssv3" in vuln:
                cvss_score = vuln["cvssv3"].get("baseScore", "N/A")
            elif "cvssv2" in vuln:
                cvss_score = vuln["cvssv2"].get("score", "N/A")

            description = vuln.get("description", "")
            if len(description) > 200:
                description = description[:200] + "..."

            vulns_by_severity[severity].append({
                "name": vuln.get("name", ""),
                "dependency": dep_name,
                "severity": severity,
                "cvss_score": cvss_score,
                "description": description,
            })

    return vulns_by_severity


def format_vulnerability_section(vulns_by_severity):
    """Format vulnerabilities section for markdown."""
    total = sum(len(v) for v in vulns_by_severity.values())

    if total == 0:
        return "## ✅ Vulnerability Status\n\nNo vulnerabilities found\n\n"

    result = ""
    severity_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}

    for severity in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        items = vulns_by_severity[severity]
        if not items:
            continue
        emoji = severity_emoji.get(severity, "⚪")
        result += f"## {emoji} {severity} Vulnerabilities ({len(items)})\n\n"
        result += "| CVE | Dependency | CVSS Score | Description |\n"
        result += "|-----|------------|------------|-------------|\n"
        for item in items:
            result += f"| {item['name']} | `{item['dependency']}` | {item['cvss_score']} | {item['description']} |\n"
        result += "\n"

    return result


def build_markdown_report(report, vulns_by_severity):
    """Build the complete markdown report."""
    total_deps = len(report.get("dependencies", []))
    total_vulns = sum(len(v) for v in vulns_by_severity.values())

    md_content = "# OWASP Dependency Check Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"
    md_content += f"- **Dependencies scanned**: {total_deps}\n"
    md_content += f"- **Total vulnerabilities**: {total_vulns}\n"
    md_content += f"  - 🔴 CRITICAL: {len(vulns_by_severity['CRITICAL'])}\n"
    md_content += f"  - 🟠 HIGH: {len(vulns_by_severity['HIGH'])}\n"
    md_content += f"  - 🟡 MEDIUM: {len(vulns_by_severity['MEDIUM'])}\n"
    md_content += f"  - 🔵 LOW: {len(vulns_by_severity['LOW'])}\n\n"

    md_content += format_vulnerability_section(vulns_by_severity)

    md_content += "## Guidelines\n\n"
    md_content += "- **CRITICAL (CVSS ≥ 9.0)**: Immediate action required\n"
    md_content += "- **HIGH (CVSS 7.0-8.9)**: Fix as soon as possible\n"
    md_content += "- **MEDIUM (CVSS 4.0-6.9)**: Fix in next release\n"
    md_content += "- **LOW (CVSS < 4.0)**: Fix when convenient\n\n"
    md_content += "- **Threshold**: CRITICAL and HIGH vulnerabilities will block merges\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [OWASP Dependency-Check](https://owasp.org/www-project-dependency-check/)\n"
    md_content += "- Reports location: `.owasp-reports/`\n"
    md_content += "  - `owasp-report.md` (this file)\n"
    md_content += "  - `dependency-check-report.json` (machine-readable)\n"

    return md_content


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from OWASP dependency check output."""
    os.makedirs(".owasp-reports", exist_ok=True)

    json_path = ".owasp-reports/dependency-check-report.json"
    report_path = ".owasp-reports/owasp-report.md"

    # Read input file
    report = read_json_report(json_path)
    vulns_by_severity = extract_vulnerabilities(report)

    # Generate report
    report_content = build_markdown_report(report, vulns_by_severity)
    write_report(report_path, report_content)

    print("✅ OWASP markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating OWASP markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
